debugging: false
automatic-updates:
  enabled: true
  method: automatic
  branch: stable
player-count-tracking:
  enabled: true
memory-tracking:
  enabled: true
  interval: 5m
performance-tracking:
  enabled: true
  interval: 5m
